const token=window.__LOCAL_TOKEN__;const headers={"x-local-token":token,"content-type":"application/json"};
const state={models:[],conversations:[],conversationId:null,messages:[],busy:false};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...headers,...options.headers}});if(!response.ok){const body=await response.json().catch(()=>({error:response.statusText}));throw new Error(body.error||response.statusText)}return response}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),3200)}
function bytes(value){if(!value)return "확인 필요";const units=["B","KB","MB","GB","TB"];let n=value,i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return `${n.toFixed(i>2?1:0)} ${units[i]}`}
function escapeHtml(value){const div=document.createElement("div");div.textContent=value;return div.innerHTML}
async function load(){try{const [statusRes,modelsRes,conversationRes]=await Promise.all([api("/api/status"),api("/api/models"),api("/api/conversations")]);const status=await statusRes.json();state.models=(await modelsRes.json()).recommended;state.conversations=await conversationRes.json();renderStatus(status);renderModels();renderConversations();renderDevice(status)}catch(error){toast(error.message)}}
function renderStatus(status){const pill=$("#runtime-pill");pill.textContent=status.runtime.reachable?`Ollama 연결됨 · ${status.runtime.installed_models.length}개 모델`:"Ollama 연결 필요";pill.classList.toggle("online",status.runtime.reachable)}
function renderModels(){const select=$("#model-select");const installed=state.models.filter(model=>model.installed);select.innerHTML=installed.length?installed.map(model=>`<option value="${model.runtime_model}">${model.display_name}</option>`).join(""):`<option value="">설치된 모델 없음</option>`;const best=state.models.find(model=>model.fit==="recommended")||state.models[0];$("#best-model").classList.remove("skeleton");$("#best-model").innerHTML=`<small>이 장치의 첫 추천</small><h2>${escapeHtml(best.display_name)}</h2><div>${escapeHtml(best.reason)}</div>`;$("#model-grid").innerHTML=state.models.map(model=>`<article class="model-card"><div class="model-meta"><span class="tag ${model.fit}">${model.fit}</span><span class="tag">${model.parameter_label}</span><span class="tag">${bytes(model.download_bytes)}</span></div><h3>${escapeHtml(model.display_name)}</h3><p>${escapeHtml(model.reason)}</p><div class="capabilities">${model.capabilities.map(c=>`<span class="tag">${c}</span>`).join("")}</div><div class="model-actions"><span class="fit">적합도 ${model.fit_score}</span><button class="install" data-model="${model.runtime_model}" ${model.installed||model.fit==="blocked"||model.fit==="runtime-required"?"disabled":""}>${model.installed?"설치됨":"설치"}</button></div><div class="progress" hidden><span style="width:0%"></span></div></article>`).join("");$$('.install').forEach(button=>button.addEventListener('click',()=>install(button)))}
async function install(button){const card=button.closest('.model-card'),bar=card.querySelector('.progress'),fill=bar.querySelector('span');button.disabled=true;bar.hidden=false;try{const response=await api(`/api/models/${encodeURIComponent(button.dataset.model)}/install`,{method:'POST'});await readSse(response,({event,data})=>{if(event==='progress'){const current=data.completed||0,total=data.total||0;fill.style.width=total?`${Math.min(100,current/total*100)}%`:'12%';if(data.status)button.textContent=data.status}});toast('모델 설치가 완료되었습니다.');await load()}catch(error){toast(error.message);button.disabled=false}}
function renderDevice(status){const d=status.device;$("#device-cards").innerHTML=`<div class="device-card"><small>운영체제</small><strong>${d.os}</strong><span>${d.architecture}</span></div><div class="device-card"><small>논리 CPU</small><strong>${d.logical_cpus}</strong><span>threads</span></div><div class="device-card"><small>총 메모리</small><strong>${bytes(d.total_memory_bytes)}</strong><span>안전 여유 포함 추천</span></div><div class="device-card"><small>로컬 런타임</small><strong>${d.runtime_reachable?'Ready':'Offline'}</strong><span>127.0.0.1 전용</span></div>`}
function renderConversations(){$("#conversation-list").innerHTML=state.conversations.map(c=>`<button class="conversation" data-id="${c.id}">${escapeHtml(c.title)}</button>`).join('');$$('.conversation').forEach(button=>button.addEventListener('click',()=>openConversation(button.dataset.id)))}
function openConversation(id){const c=state.conversations.find(item=>item.id===id);if(!c)return;state.conversationId=c.id;state.messages=c.messages;$('#model-select').value=c.model;showView('chat');renderMessages()}
function renderMessages(){const box=$('#messages');$('#empty-state').hidden=state.messages.length>0;box.innerHTML=state.messages.map(m=>`<div class="message ${m.role}">${escapeHtml(m.content)}</div>`).join('');box.scrollTop=box.scrollHeight}
function newChat(){state.conversationId=null;state.messages=[];renderMessages();$('#prompt').focus()}
async function send(event){event.preventDefault();if(state.busy)return;const prompt=$('#prompt'),model=$('#model-select').value;if(!model){toast('모델 센터에서 모델을 먼저 설치하세요.');return}const content=prompt.value.trim();if(!content)return;state.busy=true;$('#send').disabled=true;state.messages.push({role:'user',content},{role:'assistant',content:''});prompt.value='';renderMessages();const assistant=$('#messages .message:last-child');try{const response=await api('/api/chat',{method:'POST',body:JSON.stringify({conversation_id:state.conversationId,model,messages:state.messages.slice(0,-1)})});await readSse(response,({event,data})=>{if(event==='meta')state.conversationId=data.conversation_id;if(event==='token'){state.messages.at(-1).content+=data.content;assistant.textContent=state.messages.at(-1).content}if(event==='error')throw new Error(data.error)});const res=await api('/api/conversations');state.conversations=await res.json();renderConversations()}catch(error){assistant.classList.add('error');assistant.textContent=`오류: ${error.message}`}finally{state.busy=false;$('#send').disabled=false}}
async function readSse(response,onEvent){const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let boundary;while((boundary=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);let event='message',data='';for(const line of block.split('\n')){if(line.startsWith('event:'))event=line.slice(6).trim();if(line.startsWith('data:'))data+=line.slice(5).trim()}if(data)onEvent({event,data:JSON.parse(data)})}}}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}-view`));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name))}
$$('.nav').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));$('#new-chat').addEventListener('click',newChat);$('#composer').addEventListener('submit',send);$('#prompt').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();$('#composer').requestSubmit()}});load();
